steps:
- name: 'rust:1-slim-trixie'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      rustup target add wasm32-wasip1 && \
      cargo build --target=wasm32-wasip1 --release
- name: 'bash'
  script: |
    #!/usr/bin/env bash 
    cp ./target/wasm32-wasip1/release/basic_auth_header_response.wasm ./plugin.wasm
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'artifacts', 'generic', 'upload', '--source=plugin.wasm', '--version=v0.1.1', '--package=basic-auth-header-response',
    '--repository=service-extensions-wasm-plugin-generic', '--location=asia']